[package]
name = "appname"
version = "0.1.0"
authors = ["Benjamin Lee <bnllee@ucdavis.edu>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.3.4"
wasm-bindgen = "^0.2.38"
web-sys = "^0.3.6"
